version: '3.8'

services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "8080:3000"

  backend:
    build:
      context: "./server"
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: "./database"
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=propertydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
